server:
  port: 8082

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/videoclub
    username: root
    password: dbpw
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

application:
  batch:
    base-path: C:/Users/sergi/IntelliJProjects/filmo-app-batch-working-files