spring:
  application:
    name: videoclub


  datasource:
    url: jdbc:mariadb://localhost:3306/videoclub
    username: root
    password: dbpw
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB

logging:
  level:
    org.springframework.web.reactive.function.client: debug
    com.videoclub.filmoapp: debug
server:
  port: 8080

rating-api:
  urlbase: http://localhost:8081
  timeout: 10s
  oauth:
    client-id: filmo-web-client
    client-secret: RxmgLW5HLjX9vpXHZwwgUlEEf12MnWrs
