spring:
  application:
    name: videoclub
  web:
    resources:
      add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true

  datasource:
    url: jdbc:mariadb://localhost:3306/videoclub
    username: root
    password: dbpw
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework.web.reactive.function.client: debug
    com.videoclub.filmoapp: debug

server:
  port: 8080
  error:
    whitelabel:
      enabled: true
    include-stacktrace: on_param
    include-message: always
    include-binding-errors: always
    include-exception: false

rating-api:
  urlbase: http://localhost:8081
  timeout: 10s
  oauth:
    client-id: filmo-web-client
    client-secret: RxmgLW5HLjX9vpXHZwwgUlEEf12MnWrs

application:
  film:
    resources:
      base-path: C:\Users\sergi\IntelliJProjects\filmo-app-resources