spring:
  application:
    name: videoclub


  datasource:
    url: jdbc:mariadb://localhost:3306/videoclub
    username: root
    password: dbpw
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB

logging:
  level:
    sql: trace